/* =====================================================================
   WORLD COUNTRIES — name, ISO-2 code, international dial code
   Flag emoji is derived from the ISO-2 code at runtime (see app.js flag()).
   Used by the tourist registration form (country + phone dial code).
   ===================================================================== */
window.COUNTRIES = [
  { n: "Afghanistan", c: "AF", d: "93" },
  { n: "Albania", c: "AL", d: "355" },
  { n: "Algeria", c: "DZ", d: "213" },
  { n: "Andorra", c: "AD", d: "376" },
  { n: "Angola", c: "AO", d: "244" },
  { n: "Antigua and Barbuda", c: "AG", d: "1268" },
  { n: "Argentina", c: "AR", d: "54" },
  { n: "Armenia", c: "AM", d: "374" },
  { n: "Australia", c: "AU", d: "61" },
  { n: "Austria", c: "AT", d: "43" },
  { n: "Azerbaijan", c: "AZ", d: "994" },
  { n: "Bahamas", c: "BS", d: "1242" },
  { n: "Bahrain", c: "BH", d: "973" },
  { n: "Bangladesh", c: "BD", d: "880" },
  { n: "Barbados", c: "BB", d: "1246" },
  { n: "Belarus", c: "BY", d: "375" },
  { n: "Belgium", c: "BE", d: "32" },
  { n: "Belize", c: "BZ", d: "501" },
  { n: "Benin", c: "BJ", d: "229" },
  { n: "Bhutan", c: "BT", d: "975" },
  { n: "Bolivia", c: "BO", d: "591" },
  { n: "Bosnia and Herzegovina", c: "BA", d: "387" },
  { n: "Botswana", c: "BW", d: "267" },
  { n: "Brazil", c: "BR", d: "55" },
  { n: "Brunei", c: "BN", d: "673" },
  { n: "Bulgaria", c: "BG", d: "359" },
  { n: "Burkina Faso", c: "BF", d: "226" },
  { n: "Burundi", c: "BI", d: "257" },
  { n: "Cambodia", c: "KH", d: "855" },
  { n: "Cameroon", c: "CM", d: "237" },
  { n: "Canada", c: "CA", d: "1" },
  { n: "Cape Verde", c: "CV", d: "238" },
  { n: "Central African Republic", c: "CF", d: "236" },
  { n: "Chad", c: "TD", d: "235" },
  { n: "Chile", c: "CL", d: "56" },
  { n: "China", c: "CN", d: "86" },
  { n: "Colombia", c: "CO", d: "57" },
  { n: "Comoros", c: "KM", d: "269" },
  { n: "Congo (Brazzaville)", c: "CG", d: "242" },
  { n: "Congo (Kinshasa, DRC)", c: "CD", d: "243" },
  { n: "Costa Rica", c: "CR", d: "506" },
  { n: "Côte d'Ivoire", c: "CI", d: "225" },
  { n: "Croatia", c: "HR", d: "385" },
  { n: "Cuba", c: "CU", d: "53" },
  { n: "Cyprus", c: "CY", d: "357" },
  { n: "Czechia", c: "CZ", d: "420" },
  { n: "Denmark", c: "DK", d: "45" },
  { n: "Djibouti", c: "DJ", d: "253" },
  { n: "Dominica", c: "DM", d: "1767" },
  { n: "Dominican Republic", c: "DO", d: "1809" },
  { n: "Ecuador", c: "EC", d: "593" },
  { n: "Egypt", c: "EG", d: "20" },
  { n: "El Salvador", c: "SV", d: "503" },
  { n: "Equatorial Guinea", c: "GQ", d: "240" },
  { n: "Eritrea", c: "ER", d: "291" },
  { n: "Estonia", c: "EE", d: "372" },
  { n: "Eswatini", c: "SZ", d: "268" },
  { n: "Ethiopia", c: "ET", d: "251" },
  { n: "Fiji", c: "FJ", d: "679" },
  { n: "Finland", c: "FI", d: "358" },
  { n: "France", c: "FR", d: "33" },
  { n: "Gabon", c: "GA", d: "241" },
  { n: "Gambia", c: "GM", d: "220" },
  { n: "Georgia", c: "GE", d: "995" },
  { n: "Germany", c: "DE", d: "49" },
  { n: "Ghana", c: "GH", d: "233" },
  { n: "Greece", c: "GR", d: "30" },
  { n: "Grenada", c: "GD", d: "1473" },
  { n: "Guatemala", c: "GT", d: "502" },
  { n: "Guinea", c: "GN", d: "224" },
  { n: "Guinea-Bissau", c: "GW", d: "245" },
  { n: "Guyana", c: "GY", d: "592" },
  { n: "Haiti", c: "HT", d: "509" },
  { n: "Honduras", c: "HN", d: "504" },
  { n: "Hong Kong", c: "HK", d: "852" },
  { n: "Hungary", c: "HU", d: "36" },
  { n: "Iceland", c: "IS", d: "354" },
  { n: "India", c: "IN", d: "91" },
  { n: "Indonesia", c: "ID", d: "62" },
  { n: "Iran", c: "IR", d: "98" },
  { n: "Iraq", c: "IQ", d: "964" },
  { n: "Ireland", c: "IE", d: "353" },
  { n: "Israel", c: "IL", d: "972" },
  { n: "Italy", c: "IT", d: "39" },
  { n: "Jamaica", c: "JM", d: "1876" },
  { n: "Japan", c: "JP", d: "81" },
  { n: "Jordan", c: "JO", d: "962" },
  { n: "Kazakhstan", c: "KZ", d: "7" },
  { n: "Kenya", c: "KE", d: "254" },
  { n: "Kiribati", c: "KI", d: "686" },
  { n: "Kosovo", c: "XK", d: "383" },
  { n: "Kuwait", c: "KW", d: "965" },
  { n: "Kyrgyzstan", c: "KG", d: "996" },
  { n: "Laos", c: "LA", d: "856" },
  { n: "Latvia", c: "LV", d: "371" },
  { n: "Lebanon", c: "LB", d: "961" },
  { n: "Lesotho", c: "LS", d: "266" },
  { n: "Liberia", c: "LR", d: "231" },
  { n: "Libya", c: "LY", d: "218" },
  { n: "Liechtenstein", c: "LI", d: "423" },
  { n: "Lithuania", c: "LT", d: "370" },
  { n: "Luxembourg", c: "LU", d: "352" },
  { n: "Macau", c: "MO", d: "853" },
  { n: "Madagascar", c: "MG", d: "261" },
  { n: "Malawi", c: "MW", d: "265" },
  { n: "Malaysia", c: "MY", d: "60" },
  { n: "Maldives", c: "MV", d: "960" },
  { n: "Mali", c: "ML", d: "223" },
  { n: "Malta", c: "MT", d: "356" },
  { n: "Marshall Islands", c: "MH", d: "692" },
  { n: "Mauritania", c: "MR", d: "222" },
  { n: "Mauritius", c: "MU", d: "230" },
  { n: "Mexico", c: "MX", d: "52" },
  { n: "Micronesia", c: "FM", d: "691" },
  { n: "Moldova", c: "MD", d: "373" },
  { n: "Monaco", c: "MC", d: "377" },
  { n: "Mongolia", c: "MN", d: "976" },
  { n: "Montenegro", c: "ME", d: "382" },
  { n: "Morocco", c: "MA", d: "212" },
  { n: "Mozambique", c: "MZ", d: "258" },
  { n: "Myanmar", c: "MM", d: "95" },
  { n: "Namibia", c: "NA", d: "264" },
  { n: "Nauru", c: "NR", d: "674" },
  { n: "Nepal", c: "NP", d: "977" },
  { n: "Netherlands", c: "NL", d: "31" },
  { n: "New Zealand", c: "NZ", d: "64" },
  { n: "Nicaragua", c: "NI", d: "505" },
  { n: "Niger", c: "NE", d: "227" },
  { n: "Nigeria", c: "NG", d: "234" },
  { n: "North Korea", c: "KP", d: "850" },
  { n: "North Macedonia", c: "MK", d: "389" },
  { n: "Norway", c: "NO", d: "47" },
  { n: "Oman", c: "OM", d: "968" },
  { n: "Pakistan", c: "PK", d: "92" },
  { n: "Palau", c: "PW", d: "680" },
  { n: "Palestine", c: "PS", d: "970" },
  { n: "Panama", c: "PA", d: "507" },
  { n: "Papua New Guinea", c: "PG", d: "675" },
  { n: "Paraguay", c: "PY", d: "595" },
  { n: "Peru", c: "PE", d: "51" },
  { n: "Philippines", c: "PH", d: "63" },
  { n: "Poland", c: "PL", d: "48" },
  { n: "Portugal", c: "PT", d: "351" },
  { n: "Qatar", c: "QA", d: "974" },
  { n: "Romania", c: "RO", d: "40" },
  { n: "Russia", c: "RU", d: "7" },
  { n: "Rwanda", c: "RW", d: "250" },
  { n: "Saint Kitts and Nevis", c: "KN", d: "1869" },
  { n: "Saint Lucia", c: "LC", d: "1758" },
  { n: "Saint Vincent and the Grenadines", c: "VC", d: "1784" },
  { n: "Samoa", c: "WS", d: "685" },
  { n: "San Marino", c: "SM", d: "378" },
  { n: "São Tomé and Príncipe", c: "ST", d: "239" },
  { n: "Saudi Arabia", c: "SA", d: "966" },
  { n: "Senegal", c: "SN", d: "221" },
  { n: "Serbia", c: "RS", d: "381" },
  { n: "Seychelles", c: "SC", d: "248" },
  { n: "Sierra Leone", c: "SL", d: "232" },
  { n: "Singapore", c: "SG", d: "65" },
  { n: "Slovakia", c: "SK", d: "421" },
  { n: "Slovenia", c: "SI", d: "386" },
  { n: "Solomon Islands", c: "SB", d: "677" },
  { n: "Somalia", c: "SO", d: "252" },
  { n: "South Africa", c: "ZA", d: "27" },
  { n: "South Korea", c: "KR", d: "82" },
  { n: "South Sudan", c: "SS", d: "211" },
  { n: "Spain", c: "ES", d: "34" },
  { n: "Sri Lanka", c: "LK", d: "94" },
  { n: "Sudan", c: "SD", d: "249" },
  { n: "Suriname", c: "SR", d: "597" },
  { n: "Sweden", c: "SE", d: "46" },
  { n: "Switzerland", c: "CH", d: "41" },
  { n: "Syria", c: "SY", d: "963" },
  { n: "Taiwan", c: "TW", d: "886" },
  { n: "Tajikistan", c: "TJ", d: "992" },
  { n: "Tanzania", c: "TZ", d: "255" },
  { n: "Thailand", c: "TH", d: "66" },
  { n: "Timor-Leste", c: "TL", d: "670" },
  { n: "Togo", c: "TG", d: "228" },
  { n: "Tonga", c: "TO", d: "676" },
  { n: "Trinidad and Tobago", c: "TT", d: "1868" },
  { n: "Tunisia", c: "TN", d: "216" },
  { n: "Türkiye", c: "TR", d: "90" },
  { n: "Turkmenistan", c: "TM", d: "993" },
  { n: "Tuvalu", c: "TV", d: "688" },
  { n: "Uganda", c: "UG", d: "256" },
  { n: "Ukraine", c: "UA", d: "380" },
  { n: "United Arab Emirates", c: "AE", d: "971" },
  { n: "United Kingdom", c: "GB", d: "44" },
  { n: "United States", c: "US", d: "1" },
  { n: "Uruguay", c: "UY", d: "598" },
  { n: "Uzbekistan", c: "UZ", d: "998" },
  { n: "Vanuatu", c: "VU", d: "678" },
  { n: "Vatican City", c: "VA", d: "379" },
  { n: "Venezuela", c: "VE", d: "58" },
  { n: "Vietnam", c: "VN", d: "84" },
  { n: "Yemen", c: "YE", d: "967" },
  { n: "Zambia", c: "ZM", d: "260" },
  { n: "Zimbabwe", c: "ZW", d: "263" }
];
